General : 
  agent_type : dqn_heuristic # dqn_vanilla, dqn_heuristic, dqn_rnd, random, dyna
  n_episodes : 1000

Files :
  runs_dir : ../runs

DQN : 
  Qs_update_period : 3

Dyna : 

Heuristic :
  degree : 3
  reward_scale : 10

RND : 
  reward_factor : 0.1
#  n_hidden : 128
#  n_layers : 2
  