General : 
  agent_type : dqn_rnd # dqn_vanilla, dqn_heuristic, dqn_rnd, random, dyna
  n_episodes : 300

Files :
  runs_dir : ../runs

DQN : 
  Qs_NN_update_period : 3

RND : 
  reward_factor : 10.0
#  n_hidden : 128
#  n_layers : 2
  