General : 
  agent_type : dqn_heuristic # dqn_vanilla, dqn_heuristic, dqn_rnd, random, dyna
  n_episodes : 200

Files :
  runs_dir : ../runs

DQN : 
  Qs_NN_update_period : 5

Heuristic :
  degree : 2
  reward_scale : 3.5

  