General : 
  agent_type : dqn_heuristic # dqn_vanilla, dqn_heuristic, dqn_rnd, random, dyna
  n_eps : 30

Files :
  out_dir : ../runs
  out_file : dqn_heuristic_d=2_r=0.1

DQN : 
  update_tau : 3

Dyna : 

Heuristic :
  degree : 2
  reward_scale : 0.1

RND : 
  reward_factor : 0.1
#  n_hidden : 128
#  n_layers : 2
  