General : 
  agent_type : dqn_heuristic # dqn_vanilla, dqn_heuristic, dqn_rnd, random, dyna
  n_episodes : 600

Files :
  runs_dir : ../runs

DQN : 
  Qs_NN_update_period : 3

Heuristic :
  degree : 2
  reward_scale : 10.0

  